version: "3"

services:
  ftp:
        image: stilliard/pure-ftpd:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.3"
        ports:
          - "22:22"
        networks:
          - overlay
  mongo:
        image: tutum/mongodb:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.5"
        ports:
          - "27017:27017"
        environment:
            MONGODB_USER: "admin"
            MONGODB_PASS: "123456"
            MONGODB_DATABASE: "clb"
  apprun:
        image: clbproject/clbapp:latest
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.5"
        ports:
          - "8080:8080"
networks:
  overlay:


