version: "3"

services:
  mongo:
        image: mongo:3.6
        deploy:
          replicas: 1
          mode: replicated
          resources:
            limits:
              cpus: "0.3"
        ports:
          - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "admin"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
networks:
  overlay:


